using DevExpress.XtraEditors;
using Punto_Venta.Model.EF;
using System;
using System.Data.Entity;
using System.Windows.Forms;

namespace Punto_Venta.View.Mdi
{
    public partial class mdiClients : XtraForm
    {
        public string CedulaSeleccionada { get; private set; }
        public string NombreSeleccionado { get; private set; }
        public int idClienteSeleccionado { get; private set; }

        public mdiClients ( )
        {
            InitializeComponent();
            Cursor.Current = Cursors.WaitCursor;

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Punto_Venta.Model.EF.Punto_ventasEntities dbContext = new Punto_Venta.Model.EF.Punto_ventasEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Maestro_Clientes.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControlClients.DataSource = dbContext.Maestro_Clientes.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


        }

        private void gridViewClients_DoubleClick (object sender, EventArgs e)
        {
       
            var clienteSeleccionado = ObtenerClienteSeleccionado();

            // Asignar los valores seleccionados a las propiedades
            CedulaSeleccionada = clienteSeleccionado.cedula;
            NombreSeleccionado = clienteSeleccionado.nombre;
            idClienteSeleccionado =clienteSeleccionado.idCliente ;

            // Cerrar el formulario después de seleccionar un cliente
            this.Close();
        }

        private Maestro_Clientes ObtenerClienteSeleccionado ( )
        {
            
            var selectedRow = gridViewClients.GetFocusedRow() as Maestro_Clientes; // Asegúrate de reemplazar "Maestro_Clientes" con el tipo real de tus entidades
            return selectedRow;
        }
    }
}
