//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta.Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Punto_ventasEntities : DbContext
    {
        public Punto_ventasEntities()
            : base("name=Punto_ventasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria_productos> Categoria_productos { get; set; }
        public virtual DbSet<Detalles_ventas> Detalles_ventas { get; set; }
        public virtual DbSet<Maestro_Cliente> Maestro_Cliente { get; set; }
        public virtual DbSet<Maestro_ctasxcobrar> Maestro_ctasxcobrar { get; set; }
        public virtual DbSet<Maestro_Detalles_ctasxcobrar> Maestro_Detalles_ctasxcobrar { get; set; }
        public virtual DbSet<Maestro_ventas> Maestro_ventas { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
