//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_ctasxcobrar
    {
        public int Id_detalleCxC { get; set; }
        public Nullable<int> Id_CxC { get; set; }
        public Nullable<int> Id_Transaccion { get; set; }
        public Nullable<int> Id_TipoTransaccion { get; set; }
        public Nullable<int> Ref_IdTransaccion { get; set; }
        public Nullable<decimal> Monto_Abonado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
