//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_ventas
    {
        public int Id_detallesVentas { get; set; }
        public Nullable<int> Id_venta { get; set; }
        public Nullable<int> Id_producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio_venta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Maestro_ventas Maestro_ventas { get; set; }
    }
}
