//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id_Factura { get; set; }
        public int Id_Venta { get; set; }
        public int Id_TipoTransaccion { get; set; }
        public Nullable<int> Id_Transaccion { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int Id_Cliente { get; set; }
        public decimal Total { get; set; }
        public decimal Total_Pagado { get; set; }
        public string EstadoPago { get; set; }
    }
}
