//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro_ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maestro_ventas()
        {
            this.Detalles_ventas = new HashSet<Detalles_ventas>();
        }
    
        public int Id_venta { get; set; }
        public Nullable<int> Id_TipoTransaccion { get; set; }
        public Nullable<int> Id_Transaccion { get; set; }
        public Nullable<int> Id_cliente { get; set; }
        public Nullable<decimal> Monto_total { get; set; }
        public Nullable<decimal> Monto_recibido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_ventas> Detalles_ventas { get; set; }
    }
}
