//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punto_Venta.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalles_ventas = new HashSet<Detalles_ventas>();
            this.Maestro_ventas = new HashSet<Maestro_ventas>();
        }
    
        public int Id_producto { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio_compra { get; set; }
        public Nullable<decimal> Precio_venta { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Existencia { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Id_categoria { get; set; }
    
        public virtual Categoria_productos Categoria_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_ventas> Detalles_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maestro_ventas> Maestro_ventas { get; set; }
    }
}
